version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
#    volumes:
#      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "maybe"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "dev_phpmyadmin"
    restart: always
    ports:
      - 9090:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

  app:
    container_name: bootcampUser
    depends_on:
      - mysql
    build: ./
    restart: no
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysql:3306/maybe",
          "spring.datasource.username" : "user",
          "spring.datasource.password" : "password",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "none"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
