INSERT INTO `user`(
    email,
    NAME,
    patronymic,
    role,
    surname,
    id
)
VALUES
("william_new@mail.com", "William", "Brown", "CUSTOMER_USER", "Smith", "678"),
("sophia_new@mail.com", "Sophia", "Miller", "CUSTOMER_USER", "Johnson", "679"),
("oliver_new@mail.com", "Oliver", "Davis", "SECURE_API_USER", "Williams", "680"),
("emma_new@mail.com", "Emma", "Martinez", "SALE_USER", "Jones", "681"),
("ava_new@mail.com", "Ava", "Johnson", "SECURE_API_USER", "Garcia", "682"),
("james_new@mail.com", "James", "Thomas", "CUSTOMER_USER", "Rodriguez", "683"),
("noah_new@mail.com", "Noah", "Lee", "CUSTOMER_USER", "Martinez", "684"),
("liam_new@mail.com", "Liam", "Hernandez", "SALE_USER", "Lopez", "685"),
("elijah_new@mail.com", "Elijah", "Wilson", "SECURE_API_USER", "Gonzalez", "686"),
("charlotte_new@mail.com", "Charlotte", "Walker", "CUSTOMER_USER", "Moore", "687"),
("isabella_new@mail.com", "Isabella", "Perez", "CUSTOMER_USER", "Taylor", "688"),
("harper_new@mail.com", "Harper", "Lee", "SECURE_API_USER", "Clark", "689"),
("mia_new@mail.com", "Mia", "Lewis", "SALE_USER", "Hall", "690"),
("sophia_new2@mail.com", "Sophia", "Scott", "CUSTOMER_USER", "Lopez", "691"),
("oliver_new2@mail.com", "Oliver", "Adams", "CUSTOMER_USER", "White", "692"),
("james_new2@mail.com", "James", "Allen", "SECURE_API_USER", "Thomas", "693"),
("emma_new2@mail.com", "Emma", "Baker", "SALE_USER", "Lee", "694"),
("liam_new2@mail.com", "Liam", "Cook", "CUSTOMER_USER", "Perez", "695"),
("olivia_new@mail.com", "Olivia", "Cooper", "CUSTOMER_USER", "Gonzalez", "696"),
("noah_new2@mail.com", "Noah", "Evans", "SECURE_API_USER", "King", "697"),
("william_new2@mail.com", "William", "Foster", "SALE_USER", "Morris", "698"),
("ava_new2@mail.com", "Ava", "Gray", "CUSTOMER_USER", "Ward", "699"),
("charlotte_new2@mail.com", "Charlotte", "Green", "CUSTOMER_USER", "Turner", "700"),
("james_new3@mail.com", "James", "Harris", "SECURE_API_USER", "Martinez", "701"),
("isabella_new2@mail.com", "Isabella", "Hill", "SALE_USER", "Young", "702"),
("ava_new3@mail.com", "Ava", "Jackson", "CUSTOMER_USER", "Hall", "703"),
("liam_new3@mail.com", "Liam", "Johnson", "CUSTOMER_USER", "Diaz", "704"),
("emma_new3@mail.com", "Emma", "King", "SECURE_API_USER", "Rodriguez", "705"),
("oliver_new3@mail.com", "Oliver", "Lee", "SALE_USER", "Smith", "706"),
("noah_new3@mail.com", "Noah", "Lewis", "CUSTOMER_USER", "Brown", "707"),
("james_new4@mail.com", "James", "Martin", "CUSTOMER_USER", "Williams", "708"),
("ava_new4@mail.com", "Ava", "Martinez", "SECURE_API_USER", "Jones", "709"),
("emma_new4@mail.com", "Emma", "Miller", "SALE_USER", "Garcia", "710"),
("liam_new4@mail.com", "Liam", "Mitchell", "CUSTOMER_USER", "Rodriguez", "711"),
("olivia_new2@mail.com", "Olivia", "Moore", "CUSTOMER_USER", "Hernandez", "712"),
("noah_new4@mail.com", "Noah", "Morgan", "SECURE_API_USER", "Lopez", "713"),
("william_new3@mail.com", "William", "Morris", "SALE_USER", "Gonzalez", "714"),
("sophia_new3@mail.com", "Sophia", "Nelson", "CUSTOMER_USER", "Martinez", "715"),
("emma_new5@mail.com", "Emma", "Parker", "CUSTOMER_USER", "Clark", "716"),
("ava_new5@mail.com", "Ava", "Perez", "SECURE_API_USER", "Hall", "717"),
("james_new5@mail.com", "James", "Phillips", "SALE_USER", "White", "718"),
("oliver_new4@mail.com", "Oliver", "Powell", "CUSTOMER_USER", "Taylor", "719"),
("sophia_new4@mail.com", "Sophia", "Price", "CUSTOMER_USER", "Clark", "720"),
("emma_new6@mail.com", "Emma", "Reed", "SECURE_API_USER", "Thomas", "721"),
("william_new4@mail.com", "William", "Rogers", "SALE_USER", "Lee", "722"),
("olivia_new3@mail.com", "Olivia", "Ross", "CUSTOMER_USER", "Poll", "3242")
